Preliminary translation
CraftStarStudio/lwjglbook-bookcontents-zh_CN pull request #1
Opened 2021-06-23 07:15 UTC by WUTONK

Initial translation into Chinese, code comments to be processed

2021-06-24 12:11 UTC, Cubik65536 requested changes
完没完成？没有至少写Convert to draft

2021-06-24 12:11 UTC, Cubik65536 commented on chapter04/chapter4.md
> +// Unbind the VBO 解除VBO绑定
注释要不只写中文要不只写英语

2021-06-24 14:11 UTC, Cubik65536 commented
@WUTONK 已转换成Draft，下次再有正在进行的工作自己去转

2021-06-24 17:41 UTC, PencilCore approved these changes
Hope you can decrease the blank lines between paragraphs, or not the book seems too overstaffed.

2021-06-24 17:43 UTC, PencilCore commented on chapter04/chapter4.md
> +让我给你们这些有这种想法的人一个建议。它实际上更简单、更灵活。你只需要给它一个机：现代的OpenGL让你一次思考一个问题，它让你以一种更有逻辑的方式组织你的代码和进程。
> 你只需要给它一个机：
应是
你只需要给它一个机会：

2021-06-27 16:33 UTC, Cubik65536 commented
提交内包含不属于第四章的内容，还有，注释**只写中文**，**不要英语**

2021-06-27 16:33 UTC, closed without merging

2021-06-27 16:33 UTC, Cubik65536 commented
不接受该Pull request