Chapter 1 translation completed!
CraftStarStudio/lwjglbook-bookcontents-zh_CN pull request #3
Opened 2021-06-24 17:27 UTC by PencilCore

Initial translation into Chinese, code comments to be processed

2021-06-24 17:46 UTC, WUTONK reviewed
翻译的很不错，期待你修正后的版本

2021-06-24 17:46 UTC, WUTONK commented on chapter01/chapter1.md
> +# 第一步
改成“第一次”

2021-06-24 17:46 UTC, WUTONK commented on chapter01/chapter1.md
> +LWJGL 是一个像 OpenGL 的包装器的底层 API.如果您想在短时间内开始制作 3D 游戏的话, 或许您应当考虑其他的 API,比如 \[JmonkeyEngine\]. 要使用这些底层API, 您将需要理解许多概念并写下许多代码来获得您心意的结果, 这样做的好处就是, 您将会更好地理解与掌握 3D 图形系统.
改为“来获得你想要的结果”

2021-06-24 17:59 UTC, PencilCore commented on chapter01/chapter1.md
> +# 第一步
为何，step应当翻译成步更妥当吧，请拿出理由。

2021-06-24 17:59 UTC, PencilCore commented on chapter01/chapter1.md
> +LWJGL 是一个像 OpenGL 的包装器的底层 API.如果您想在短时间内开始制作 3D 游戏的话, 或许您应当考虑其他的 API,比如 \[JmonkeyEngine\]. 要使用这些底层API, 您将需要理解许多概念并写下许多代码来获得您心意的结果, 这样做的好处就是, 您将会更好地理解与掌握 3D 图形系统.
好的

2021-06-25 01:58 UTC, PencilCore commented
修正完成，请管理组过目。

2021-06-25 02:04 UTC, PencilCore commented
请先不要审查。

2021-06-25 02:28 UTC, PencilCore commented
现在允许审查

2021-06-25 03:47 UTC, Cubik65536 commented
@CraftStarStudio/software-localization @PencilCore 下次使用draft，不要提交“暂时不要审查”或类似的comment

2021-06-25 13:56 UTC, Cubik65536 requested changes
质量足够高，但是有些需要改进的地方，期待你的下一版本

Best regards,

2021-06-25 13:56 UTC, Cubik65536 commented on chapter01/chapter1.md
> +通过 Maven 构建的项目是基于一个叫做 `pom.xml` \(Project Object Model\) 的 XML 文件上的. 这个文件用来管理项目的依赖关系与构建过程中所要进行的步骤. Maven 遵循约定大于配置的原则, 这就是说, 如果你执意使用标准的项目结构与命名规范, 那么你将没有必要在配置文件中加入源文件和编译类的位置.
> 如果你执意使用标准的项目结构与命名规范

改成 `如果你遵循标准项目结构与命名规范` 会更好一点？

2021-06-25 13:56 UTC, Cubik65536 commented on chapter01/chapter1.md
> +LWJGL 3.1 第一次尝试了一些在构建项目时的变化. 现在核心代码已经变得更加结构化, 从而使得我们在包管理上可以更加有选择性地选择我们需要的包, 而不是取而代之地使用一个庞大单一臃肿不堪的 jar 文件. 但这也需要一个代价: 你需要更仔细地一个个指定依赖关系. 但是不用担心, [下载](https://www.lwjgl.org/download) 页面包含了一个可以帮你生成 pom 文
> 第一次尝试了一些在构建项目时的变化

这里是指对项目构建方式的一些变化

> 结构化

`模块化`?

> 而不是取而代之地使用

有点绕，翻译建议：`从而使得我们可以在包管理器中随意选择我们需要的包以替代一个庞大，单一，臃肿不堪的jar文件`

2021-06-25 13:56 UTC, Cubik65536 commented on chapter01/chapter1.md
> +这些 jar 文件包含了 LWJGL 的类, 也包含了一些原生库. LWJGL 也会压缩他们, 并将他们加入 JVM 寻找库的环境变量中去.
这里是 `extracting` 解压

2021-06-25 13:56 UTC, Cubik65536 commented on chapter01/chapter1.md
> +除此之外, 每个项目都会生成一个可运行的 jar 文件 \(可通过输入 java -jar name\_of\_the\_jar.jar\ 来运行).其是通过使用可以生成带有正确属性值与 `MANIFEST.MF` 文件的 jar 文件的插件来打包的. 该文件最重要的一点就是 `Main-Class` (主类), 其设置了程序的进入点. 另外, 所有依赖关系都被设置成了在 `Class-Path
> jar 文件的插件

直接写原文的 `maven-jar-plugin`，后面可以多加个 `插件`

2021-06-25 14:02 UTC, PencilCore commented on chapter01/chapter1.md
> +通过 Maven 构建的项目是基于一个叫做 `pom.xml` \(Project Object Model\) 的 XML 文件上的. 这个文件用来管理项目的依赖关系与构建过程中所要进行的步骤. Maven 遵循约定大于配置的原则, 这就是说, 如果你执意使用标准的项目结构与命名规范, 那么你将没有必要在配置文件中加入源文件和编译类的位置.
确实，这里如果用执意的话会让读者感觉这是一种不好的行为方式。属语义错误。

2021-06-25 14:07 UTC, PencilCore commented on chapter01/chapter1.md
> +LWJGL 3.1 第一次尝试了一些在构建项目时的变化. 现在核心代码已经变得更加结构化, 从而使得我们在包管理上可以更加有选择性地选择我们需要的包, 而不是取而代之地使用一个庞大单一臃肿不堪的 jar 文件. 但这也需要一个代价: 你需要更仔细地一个个指定依赖关系. 但是不用担心, [下载](https://www.lwjgl.org/download) 页面包含了一个可以帮你生成 pom 文
确实，我有些有些过于直译了。但我希望日后在翻译中加入一些本地化元素以帮助读者理解，避免中文西化。

2021-06-25 14:16 UTC, Cubik65536 approved these changes

2021-06-25 14:17 UTC, Cubik65536 commented
@PencilCore Merged，下次不要push另外一章，或者选择开新的 `branch`，wiki会加上这个提醒

2021-06-25 14:17 UTC, merged