Update chapter4.md
CraftStarStudio/lwjglbook-bookcontents-zh_CN pull request #7
Opened 2021-06-28 14:07 UTC by WUTONK

Upload Volume 4 again

2021-06-28 15:00 UTC, Cubik65536 requested changes
请把行数对齐，不需要的换行不要换行，原来的内容是第几行现在就还是第几行

2021-06-28 15:30 UTC, WUTONK commented
已经修改

2021-06-28 15:51 UTC, Cubik65536 requested changes
还得对齐

2021-06-28 15:52 UTC, WUTONK commented
对齐了

2021-06-28 18:19 UTC, Cubik65536 requested changes
大量的问题重复出现
- **为什么标题和描述没有包含第五章**
- **为什么又多了一个空行**
- **为什么又少了一个空行**
- 语句不通顺
- 专业术语不正确

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +在本章中,我们将学习使用OpenGL渲染场景时发生的过程和三维图形基本渲染过程.如果你习惯于旧版本的OpenGL,也就是固定的函数管道,你可能会在本章结束时想知道为什么它需要如此复杂.你可能会认为,只是在屏幕上画一个简单的形状完全不需要那么多的概念和代码.让我给你们这些有这种想法的人一个建议.它实际上更简单、更灵活.你只需要给它一个机会:现代的OpenGL让你一次只思考一个问题,它让你以一种更有
> 固定的函数管道

`fixed-function pipeline`，固定渲染管线

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +图形管道由以下步骤组成：
> 图形管道

`graphics pipeline`，渲染管线

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +将一个三维表示绘制到二维屏幕的一系列步骤称为图形管道.OpenGL的第一个版本使用了一个称为固定函数管道的模型.该模型在渲染过程中采用了一组步骤,定义了一组固定的操作,程序员被限制在每个步骤可用的一组函数中.因此,可以应用的效果和操作受到API本身的限制\(例如，“set fog”或“add light”，但这些函数的实现是固定的，不能更改\).
> 固定函数管道

同上

> “set fog”或“add light”

把这段翻译了

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +但在OPENGL 2.0版本,其引入了可编程流水线渲染的概念.在这个模型中,组成图形管道的不同步骤可以通过一组称为“着色器”的特定程序来控制或编程.(可编程自定义渲染过程,而不是只能使用固定设置)下图描述了OpenGL可编程管道的简化版本:
> 可编程流水线渲染

可编程渲染管线

> 图形管道

渲染管线

> (可编程自定义渲染过程,而不是只能使用固定设置)

原文有这一段吗？

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +![Programmable pipeline](./rendering_pipeline_2.png)
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +几何体的处理阶段:连接顶点着色器变换的顶点以形成三角形.它是通过判断顶点的存储顺序并使用不同的模型对它们进行分组来实现的.那为什么是三角形呢?三角形类似于图形卡的基本工作单元.它是一个简单的几何形状,可以组合和转换来构建复杂的三维场景.此阶段还可以使用特定着色器对顶点进行分组.
> 变换

转换

> 形成

生成

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +请记住,3D加速卡专门设计来用于并行上述所有操作.为了生成最终场景,可以并行处理输入数据.(非常多的线程共同计算,参考英伟达的CUDA芯片,几千个核心共同处理,这是专为渲染图形所设计的硬件方案)
括号里的东西全删了

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +第一行是一个指令,说明了我们使用的GLSL语言的版本.下表则说明了GLSL版本、和与该版本匹配的OpenGL以及要使用的指令.\(维基百科: [https://en.wikipedia.org/wiki/OpenGL\_Shading\_Language\#Versions](https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versio
改成中文链接：https://zh.wikipedia.org/wiki/GLSL

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +第二行用来指定此着色器的输入格式.OpenGL缓冲区中的数据都可以是我们想要的任何数据,也就是说,该语言不会强制你传递具有预定义语义的特定数据结构.从着色器的角度来看,它希望接收一个包含数据的缓冲区.它可以是一个位置,一个有额外信息的位置,或者我们想要的任何位置.当顶点着色器刚刚接收一个浮点数组,填充缓冲区时,定义将由着色器处理的缓冲区块来定义.
> 或者我们想要的任何位置

`or whatever else we want`，我想我没有要说的话了

> 刚刚接收

`is just receving`，仅仅接收到

------

最后这一段完全不是你翻译的意思

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量,这到底是怎么实现的\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中
> 现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量,这到底是怎么实现的\(vec4\)？

哪里来的“这到底是怎么实现的”？

> 这些操作中的一些就不能合并

不能被同时使用

> 《3D Math Primer for Graphics and Game Development

"》"去哪了？

> 阅读Fletcher Dunn和Ian Parberry大佬的优秀著作

谁给你添油加醋的权利的？

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +现在让我们看看我们的第一个片段着色器.我们将在resources目录下创建一个名为“`fragment.fs`”的方法\(扩展名是 Fragment Shader\)位于resources目录下,包含以下内容:
> 位于resources目录下,包含以下内容:

句号。在resources目录下,包含以下内容:

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +这个叫`ShaderProgram`的构造函数在OpenGL中创建了一个新程序,并提供了添加顶点和片段着色器的方法.这些着色器被编译并附加到OpenGL程序.当附加所有着色器时,应该调用link方法,该方法负责链接所有代码,并验证所有操作是否正确.
> 这些着色器被编译并附加到OpenGL程序

这些着色器会被编译并附加到OpenGL程序

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +此方法主要用于调试目的,当游戏进入生产阶段时应将其删除.此方法尝试验证给定**当前OpenGL状态**的着色器是否正确.这意味着,在某些情况下,即使着色器是正确的,验证也可能失败,因为当前状态不够完整,无法运行着色器\(某些数据可能尚未上载\),因此,我们只需将错误消息打印到标准错误输出就好,而不是认为运行失败.
> Regarding verification, this is done through the `glValidateProgram` call.

去哪了？

> 因为当前状态不够完整,无法运行着色器

因为当前状态不够完整运行着色器

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +我们已经创建了一个实用程序类,现在它提供了一个从类路径检索文件内容的方法,此方法用于检索着色器的内容.
> 实用程序类

工具类

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +VAO就像一个包装器,它为将要存储在图形卡中的数据分组为一组一组的定义,当我们创建一个VAO时,我们得到一个标识符.我们使用该标识符来呈现它和它包含的元素,使用我们在创建期间指定的定义.
> 我们得到一个标识符

我们将会得到一个标识符

> 我们使用该标识符来呈现它和它包含的元素,使用我们在创建期间指定的定义.

我们使用该标识符和我们在创建期间指定的定义来呈现它和它包含的元素

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +让我们继续编写我们的示例.我们必须做的第一件事是将浮点数组存储到`FloatBuffer`中.这主要是因为我们必须与基于C语言的OpenGL库接口,所以我们必须将我们的float数组转换成库可以管理的东西.
> 这主要是因为我们必须与基于C语言的OpenGL库接口

你自己觉得通顺吗

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +如果你是LWJGL的早期版本使用者,那么强调几个主题是很重要的.你可能已经注意到,我们没有使用实用程序类`BufferUtils`来创建缓冲区.相反,我们使用`MemoryUtil`类.这是由于`BufferUtils`的效率不高,而且只是为向后兼容而设计的.相反,LWJGL 3则提出了两种缓冲区管理方法:
> 相反,LWJGL 3则提出了两种缓冲区管理方法:

为此,LWJGL...

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +* 大小:指定每个顶点的组件数属性\(from 1 to 4\).在这个例子中,我们传递的是三维坐标,所以它应该是3.
> \(from 1 to 4\).

翻译了啊

2021-06-28 18:19 UTC, Qubik65536 commented on chapter04/chapter4.md
> +// 关闭VAO
> 关闭VAO

解除VAO绑定

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +建一个名为`Mesh`的新的类,它将用一个位置数组作为输入,创建该模型加载到显卡中所需的VBO和VAO对象.
> In this chapter we will continue talking about how OpenGL renders things. In order to tidy up our code a little bit

都去哪了？

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +我们将在`DummyGame`类中创建`Mesh`实例,从`Renderer``init`方法中删除VAO和VBO代码.`Renderer`类中的render方法也将接受要渲染的网格实例.`cleanup`方法也将得到简化,因为`Mesh`类已经提供了释放VAO和VBO资源的方法.
> `Renderer``init`

原来中间有空格为什么删了？

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
107行的东西为什么在108行上？

2021-06-28 18:19 UTC, Cubik65536 commented on chapter04/chapter4.md
> +![Triangle](./triangle_coordinates.png)
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Cubik65536 commented on chapter04/chapter4.md
> +![Triangle game](./triangle_window.png)
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +现在，你应该看到这样渲染的四边形:
空行去哪了？

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +![Quad coordinates](./quad_coordinates.png)
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +![Dolphin](./dolphin.png)
[]内的是图片描述，需要翻译

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么多了个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +因此,我们需要修改`Mesh`类,以接受另一个参数 -- 一个索引数组.现在要绘制的顶点数将是该索引数组的数.
为什么少了个空行
------
> 将是该索引数组的数

be the length of that indices array，该索引数组的长度

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +创建存储位置的VBO后,需要创建另一个保存索引的VBO.因此,我们需要重命名保存位置,和VBO标识符的标识符,并为索引VBO\(`idxVboId`\)创建一个新的标识符.这和创建VBO的过程类似,不过类型现在是`GL_ELEMENT_ARRAY_BUFFER`.
> 因此,我们需要重命名保存位置,和VBO标识符的标识符,并为索引VBO\(`idxVboId`\)创建一个新的标识符.

> So we rename the identifier that holds the identifier for the positions VBO and create a new one for the index VBO \(`idxVboId`\).

因此，我们将重命名保存着存储位置的VBO的标识符的标识符，然后为索引VBO\(`idxVboId`\)创建一个新的标识符

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +* 类型:指定索引数据中的值的类型,在这种情况下,我们使用整数.
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +
为什么又多了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +现在,我们的片段着色器接收顶点着色器处理的颜色作为输入,并使用它来生成颜色.
为什么又少了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +我们现在可以将这样的颜色数组传递给`Mesh`类,以便为我们的四边形添加一些颜色.
为什么又少了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +然后我们将会得到一个像这样的花式彩色四边形！:
为什么又少了一个空行

2021-06-28 18:19 UTC, Cubik65536 commented on chapter05/chapter5.md
> +![Coloured quad](./coloured_quad.png)
为什么又少了一个空行

------

[]内的是图片描述，需要翻译

2021-06-29 13:31 UTC, PencilCore commented
我求求你了，在使用半角字符时，请在句子和句子间加空格

2021-06-29 13:34 UTC, Cubik65536 commented
> 我求求你了，在使用半角字符时，请在句子和句子间加空格

ICU欢迎您

2021-06-29 13:42 UTC, PencilCore reviewed
差不多了，这些参考下，然后让cubik并掉吧

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +![图形管线](./rendering_pipeline.png)
？渲染管线

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +但在OPENGL 2.0版本,其引入了可编程渲染管线的概念.在这个模型中,组成图形管道的不同步骤可以通过一组称为“着色器”的特定程序来控制或编程.下图描述了OpenGL可编程管道的简化版本:
最后一句话，管道—管线

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +渲染开始将顶点缓冲区形式的顶点列表作为其输入.但,什么是顶点?顶点是描述二维或三维空间中的点的数据结构.你该如何描述三维空间中的一个点?————通过指定其x、y和z坐标.那什么是顶点缓冲区?顶点缓冲区是另一种数据结构,它通过使用顶点数组,打包需要渲染的所有顶点,并使这些信息可供图形管道中的着色器使用.
破折号（半角）= -

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +渲染开始将顶点缓冲区形式的顶点列表作为其输入.但,什么是顶点?顶点是描述二维或三维空间中的点的数据结构.你该如何描述三维空间中的一个点?————通过指定其x、y和z坐标.那什么是顶点缓冲区?顶点缓冲区是另一种数据结构,它通过使用顶点数组,打包需要渲染的所有顶点,并使这些信息可供图形管道中的着色器使用.
x, y 和 z 坐标？

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +渲染开始将顶点缓冲区形式的顶点列表作为其输入.但,什么是顶点?顶点是描述二维或三维空间中的点的数据结构.你该如何描述三维空间中的一个点?————通过指定其x、y和z坐标.那什么是顶点缓冲区?顶点缓冲区是另一种数据结构,它通过使用顶点数组,打包需要渲染的所有顶点,并使这些信息可供图形管道中的着色器使用.
最后一句话老问题

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中w表示一个额外的维度
不要用书名号，用引号

2021-06-29 13:42 UTC, PencilCore commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中w表示一个额外的维度
英文书籍没有用书名号的，都用斜体或引号

2021-06-29 13:51 UTC, Cubik65536 requested changes
还有该改的东西没改

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +![图形管线](./rendering_pipeline.png)
`渲染管线由以下步骤组成` 刚刚改过

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +几何体的处理阶段:连接顶点着色器转换的顶点以生成三角形.它是通过判断顶点的存储顺序并使用不同的模型对它们进行分组来实现的.那为什么是三角形呢?三角形类似于图形卡的基本工作单元.它是一个简单的几何形状,可以组合和转换来构建复杂的三维场景.此阶段还可以使用特定着色器对顶点进行分组.
连接顶点着色器转换顶点以生成三角形

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +第一行是一个指令,说明了我们使用的GLSL语言的版本.下表则说明了GLSL版本、和与该版本匹配的OpenGL以及要使用的指令.\(维基百科: [https://en.wikipedia.org/wiki/OpenGL\_Shading\_Language\#Versions](https://zh.wikipedia.org/wiki/GLSL)\).
`[https://en.wikipedia.org/wiki/OpenGL\_Shading\_Language\#Versions]` 里的东西为什么给改了？

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中w表示一个额外的维度
这个可以不用改，中文文章

> 不要用书名号，用引号

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +现在让我们看看我们的第一个片段着色器.我们将在resources目录下创建一个名为“`fragment.fs`”的方法\(扩展名是 Fragment Shader\).位于resources目录下,包含以下内容:
在resources目录下,包含以下内容:

2021-06-29 13:51 UTC, Cubik65536 commented on chapter04/chapter4.md
> +关于验证,这是通过`glValidateProgram`调用完成的.此方法主要用于调试目的,当游戏进入生产阶段时应将其删除.此方法尝试验证给定**当前OpenGL状态**的着色器是否正确.这意味着,在某些情况下,即使着色器是正确的,验证也可能失败,因为当前状态不够完整运行着色器\(某些数据可能尚未上载\),因此,我们只需将错误消息打印到标准错误输出就好,而不是认为运行失败.
> 关于验证,这是通过`glValidateProgram`调用完成的

关于验证,这是通过调用`glValidateProgram`完成的

2021-06-29 13:52 UTC, Cubik65536 commented
第五章完全没动？

2021-06-29 14:38 UTC, PencilCore commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中w表示一个额外的维度
> 这个可以不用改，中文文章
> 
> 
> 
> > 不要用书名号，用引号

https://www.zhihu.com/question/33271098，请参考

2021-06-29 15:57 UTC, Cubik65536 requested changes

2021-06-29 15:57 UTC, Cubik65536 commented on chapter04/chapter4.md
> +第一行是一个指令,说明了我们使用的GLSL语言的版本.下表则说明了GLSL版本、和与该版本匹配的OpenGL以及要使用的指令.\(维基百科: [https://zh.wikipedia.org/wiki/OpenGL\_Shading\_Language\#Versions](https://zh.wikipedia.org/wiki/GLSL)\).
你确定中文维基百科链接是这个？你把后面那一段复制粘贴很难？

2021-06-29 15:57 UTC, Cubik65536 commented on chapter04/chapter4.md
> +![渲染管线由以下步骤组成](./rendering_pipeline.png)
`![渲染管线](./rendering_pipeline.png)`

2021-06-29 15:57 UTC, Cubik65536 commented on chapter04/chapter4.md
> +着色器有一个主块,就像任何其他的C语言程序一样,在本案例中非常简单,它要做的只是返回输出变量`gl_Position`中接收到的位置,而不应用任何转换.现在你可能想知道为什么三个属性的向量会被转换成四个属性的向量\(vec4\)？这是因为`gl_Position`使用的是齐次坐标格式,因此预期结果为vec4格式.也就是说,它需要某种形式的四个变量\(x，y，z，w\)s,其中w表示一个额外的维度
书名号倒是改了啊！

2021-07-05 23:21 UTC, Cubik65536 commented
项目暂停，待恢复之后重新Open

2021-07-05 23:21 UTC, closed without merging

2021-07-25 19:05 UTC, KevinZonda reviewed
This work is amazing! @Cubik65536

2021-07-25 19:33 UTC, Cubik65536 commented
> This work is amazing! @Cubik65536

Do you want to join this ~~垃圾~~ studio?

2021-07-25 21:02 UTC, KevinZonda commented
> > This work is amazing! @Cubik65536
> 
> Do you want to join this ~垃圾~ studio?

Yeah, pls!